title: FAQ Communauté RI&IN
description: FAQ des utilisateurs du serveur mastodon riin.fr
theme: just-the-docs

url: https://aide.riin.fr

logo: "/assets/images/riin_top_banner.png"

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

footer_content: "Site édité par l'association [CECyF](https://www.cecyf.fr)"
